### ISSUE TITLE
problems with Capistrano 2.x branch on OS X Yosemite

### ISSUE THREAD

**Issue by kisakov** [capistrano/notification-center#7]
In notification-center v0.0.2 there is dependency terminal-notifier ~> 1.4.2
But this version of terminal-notifier doesn't work with OS X Yosemite.
It fixed in new version terminal-notifier https://github.com/alloy/terminal-notifier/issues/106

Thank you!

**Comment by mattbrictson** [comment]
Realistically we will probably never address this issue, as Capistrano 2.x is no longer supported. Sorry!
